# -*- coding: utf-8 -*-
"""CodeAlpha_Task1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCpqg1_Ck2EQoUNN2OKXdyBIXkFwbDc8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Unemployment_Rate_upto_11_2020.csv")


df.columns = df.columns.str.strip()


print(df.head())

df.rename(columns={
    'Date': 'Date',
    'Region': 'Region',
    'Estimated Unemployment Rate (%)': 'UnemploymentRate'
}, inplace=True)

df['Date'] = pd.to_datetime(df['Date'])

plt.figure(figsize=(10,5))
sns.lineplot(x='Date', y='UnemploymentRate', data=df)
plt.title('Unemployment Rate Over Time')
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))
sns.boxplot(x='Region', y='UnemploymentRate', data=df)
plt.title('Unemployment Rate by Region')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

df['Month'] = df['Date'].dt.month


pivot_table = df.pivot_table(values='UnemploymentRate', index='Region', columns='Month')


plt.figure(figsize=(12,6))
sns.heatmap(pivot_table, annot=True, fmt=".1f", cmap='YlGnBu')
plt.title("Monthly Unemployment Rate by Region")
plt.xlabel("Month")
plt.ylabel("Region")
plt.show()

insights = """
Key Insights:

1. Unemployment spiked sharply during March–May 2020, reflecting COVID-19 lockdown impact.
2. Region-wise data shows states like [Region X] had consistently higher unemployment.
3. Seasonal variation shows mid-year peaks in joblessness.
4. Post-COVID recovery started around late 2020 in many regions.
"""
print(insights)